name: Web Scraper Scheduled Run

on:

  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install Dependencies
      run: |
        npm ci
        npm install -g ts-node
    
    - name: Install Chromium Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libxcomposite1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxss1 \
          libxtst6 \
          ca-certificates \
          fonts-liberation \
          libappindicator3-1 \
          libasound2 \
          libdbus-1-3 \
          libgbm1 \
          libgcc1 \
          libglib2.0-0 \
          libnspr4 \
          libpango-1.0-0 \
          fonts-noto-color-emoji \
          libx11-xcb1 \
          libxcb-dri3-0 \
          libxcb1
    
    - name: Run Web Scraper
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SCRAPE_BASE_URL: ${{ secrets.SCRAPE_BASE_URL }}
        SCRAPE_BUCKET_NAME: ${{ secrets.SCRAPE_BUCKET_NAME }}
      run: npm run start